repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.52.0  # замените на последнюю версию Ruff
    hooks:
      - id: ruff
        args: ["--fix"]  # автоматически исправляет ошибки

  - repo: https://github.com/psf/black
    rev: 23.9.1  # замените на последнюю версию Black
    hooks:
      - id: black
